In [2]:
import torch
import numpy as np

In [31]:
class Sel:
    def __init__(self):
        self.out = None
        self.device = None
sel = Sel()
sel.out = torch.ones((2,5,5))
sel.device  = torch.device("cuda")

def _encode_one_hot(sel, pos, size):
    N,H,W = sel.out.shape
    assert(pos.shape==(N,2))
    pos = pos.to(sel.device)
    one_hot = torch.zeros_like(sel.out).to(sel.device)
    src_idx = torch.Tensor(np.arange(0,size[1])).to(sel.device) #  W_
    src_idx = torch.ones(N,H,*(src_idx.shape)).to(sel.device) * src_idx.reshape(1,1,*(src_idx.shape)) # N, H, W_
#     print(pos[:,1].reshape(N,1,1))
    src_idx = src_idx+pos[:,1].reshape(N,1,1) # add the y to each row
    src_idx = src_idx.long()
    src = torch.zeros_like(sel.out).to(sel.device)
    src.scatter_(2,src_idx,1.0) #N, H, W

    idx = torch.Tensor(np.arange(0,size[0])).to(sel.device) #  H_
    idx = torch.ones(N,*(idx.shape),W).to(sel.device) * idx.reshape(1,*(idx.shape),1) # N, H_, W
    idx = idx + (pos[:,0]).reshape(N,1,1)
    
    idx = idx.long()
    one_hot.scatter_(1,idx,src)
    return one_hot
_encode_one_hot(sel, torch.Tensor([[1,1],[0,0]]), (2,2))

tensor([[[0., 0., 0., 0., 0.],
         [0., 1., 1., 0., 0.],
         [0., 1., 1., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[1., 1., 0., 0., 0.],
         [1., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], device='cuda:0')

In [14]:
b = torch.ones((2,3,2))
(b* a.reshape(1,1,-1)).shape

torch.Size([2, 3, 2])

In [32]:
a = np.random.rand(2,2,4)
print(a)
a + np.eye(2).reshape(2,2,1)

[[[0.58601455 0.04910256 0.47256636 0.38144672]
  [0.38746973 0.61341205 0.21767825 0.504149  ]]

 [[0.16064272 0.60511847 0.74579905 0.76440356]
  [0.93923179 0.93376225 0.99355835 0.69255258]]]


array([[[1.58601455, 1.04910256, 1.47256636, 1.38144672],
        [0.38746973, 0.61341205, 0.21767825, 0.504149  ]],

       [[0.16064272, 0.60511847, 0.74579905, 0.76440356],
        [1.93923179, 1.93376225, 1.99355835, 1.69255258]]])

In [33]:
np.uint8(a)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=uint8)